/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Interface.TransactionActionImplementation;
import static Main.Main.destinations;
import static Main.Main.passengerTypes;
import static Main.Main.seatTypes;
import static Main.Main.view;
import Models.Transaction;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jay Vallespin
 */
public class UpdateTransaction extends javax.swing.JFrame {
    Transaction t = new Transaction();
    int id;
    
    /**
     * Creates new form CreateTransaction
     */
    public UpdateTransaction() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        populateDestinationComboBox();
        populatePassengerTypeComboBox();
        populateSeatTypeComboBox();
    }
    
    void populateFieldsbyId(int id) {
        destinationComboBox.setSelectedIndex(t.getDestinationId());
        passengerTypeComboBox.setSelectedIndex(t.getPassengerTypeId());
        seatTypeComboBox.setSelectedIndex(t.getSeatTypeId());
        quantity.setText(String.valueOf(t.getQuantity()));
        amount.setText(String.valueOf(t.getAmount()));
        total.setText("Total: " + String.valueOf(t.getTotal()));
        change.setText("Change: " + String.valueOf(t.getChange()));
    }
    
    void populateDestinationComboBox() {
        List<Transaction> transactions = destinations();
        
        for (Transaction t : transactions) {
            destinationComboBox.addItem(t.getDestination());
        }
    }
    
    void populatePassengerTypeComboBox() {
        List<Transaction> passengerTypes = passengerTypes();
        
        for (Transaction t : passengerTypes) {
            passengerTypeComboBox.addItem(t.getPassengerType() + " - " + t.getPassengerTypePrice());
        }
    }
    
    void populateSeatTypeComboBox() {
        List<Transaction> seatTypes = seatTypes();
        
        for (Transaction t : seatTypes) {
            seatTypeComboBox.addItem(t.getSeatType() + " - " + t.getSeatTypePrice());
        }
    }
    
    void calculateTotal() {
        if (t.getPassengerTypePrice() > 0 && t.getSeatTypePrice() > 0 && t.getQuantity() > 0) {
            t.setTotal((t.getPassengerTypePrice() + t.getSeatTypePrice()) * t.getQuantity());
            total.setText("Total: " + t.getTotal());

            if (t.getAmount() >= t.getTotal()) {
                t.setChange(t.getAmount() - t.getTotal());
                change.setText("Change: " + t.getChange());
                jLabel6.setText("");
            } else {
                jLabel6.setText("Insuficient amount");
            }
        } else {
            total.setText("Total: ");
            change.setText("Change: ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        destinationComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        passengerTypeComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        seatTypeComboBox = new javax.swing.JComboBox<>();
        quantity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        change = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        searchId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Go back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Destinations");

        destinationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select destination" }));
        destinationComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                destinationComboBoxItemStateChanged(evt);
            }
        });
        destinationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Passenger Types");

        passengerTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select passenger type" }));
        passengerTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                passengerTypeComboBoxItemStateChanged(evt);
            }
        });
        passengerTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengerTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Seat Types");

        seatTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select seat type" }));
        seatTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatTypeComboBoxItemStateChanged(evt);
            }
        });
        seatTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatTypeComboBoxActionPerformed(evt);
            }
        });

        quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityActionPerformed(evt);
            }
        });
        quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityKeyReleased(evt);
            }
        });

        jLabel4.setText("No. of tickets");

        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountKeyReleased(evt);
            }
        });

        jLabel5.setText("Amount");

        total.setText("Total:");

        change.setText("Change:");

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        searchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIdActionPerformed(evt);
            }
        });
        searchId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchIdKeyReleased(evt);
            }
        });

        jLabel7.setText("Enter transaction id");

        jButton2.setText("Search ID");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchId, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(total)
                    .addComponent(change)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(update)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(destinationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(passengerTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passengerTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(change)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6))
                    .addComponent(update))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Home h = new Home();
        
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void destinationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationComboBoxActionPerformed
        
    }//GEN-LAST:event_destinationComboBoxActionPerformed

    private void passengerTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerTypeComboBoxActionPerformed

    }//GEN-LAST:event_passengerTypeComboBoxActionPerformed

    private void seatTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatTypeComboBoxActionPerformed
        
    }//GEN-LAST:event_seatTypeComboBoxActionPerformed

    private void quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityActionPerformed
        
    }//GEN-LAST:event_quantityActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        
    }//GEN-LAST:event_amountActionPerformed

    private void amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyReleased
        t.setAmount(Double.parseDouble(amount.getText()));
        calculateTotal();
    }//GEN-LAST:event_amountKeyReleased

    private void quantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityKeyReleased
        t.setQuantity(Integer.parseInt(quantity.getText()));
        calculateTotal();
    }//GEN-LAST:event_quantityKeyReleased

    private void destinationComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_destinationComboBoxItemStateChanged
        int index = (int) destinationComboBox.getSelectedIndex();
        String value = (String) destinationComboBox.getSelectedItem();
        
        t.setDestinationId(index);
        t.setDestination(value);
    }//GEN-LAST:event_destinationComboBoxItemStateChanged

    private void passengerTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_passengerTypeComboBoxItemStateChanged
        int index = (int) passengerTypeComboBox.getSelectedIndex();
        String value = (String) passengerTypeComboBox.getSelectedItem();
        
        t.setPassengerTypeId(index);
        t.setPassengerType(value);
        
        double amount = 0;
        if (index == 1) {
            amount = 50.00;
        } else if (index == 2) {
            amount = 40.00;
        } else if (index == 3) {
            amount = 45.00;
        }

        t.setPassengerTypePrice(amount);
        calculateTotal();
    }//GEN-LAST:event_passengerTypeComboBoxItemStateChanged

    private void seatTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatTypeComboBoxItemStateChanged
        int index = (int) seatTypeComboBox.getSelectedIndex();
        String value = (String) seatTypeComboBox.getSelectedItem();
        
        t.setSeatTypeId(index);
        t.setSeatType(value);
        
        double amount = 0;
        if (index == 1) {
            amount = 20.00;
        } else if (index == 2) {
            amount = 50.00;
        } else if (index == 3) {
            amount = 100.00;
        } else if (index == 4) {
            amount = 150.00;
        }
        
        t.setSeatTypePrice(amount);
        calculateTotal();
    }//GEN-LAST:event_seatTypeComboBoxItemStateChanged

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        TransactionActionImplementation tai = new TransactionActionImplementation();
        
        if (t.getAmount() < t.getTotal()) {
            JOptionPane.showMessageDialog(this, "Insuficient Balance!");
            return;
        }
        t.setCreated_at(Timestamp.valueOf(LocalDateTime.now()));
        if (tai.updateTransaction(t)) {
            JOptionPane.showMessageDialog(this, "Updated Successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Update Failed!");
        }
    }//GEN-LAST:event_updateActionPerformed

    private void searchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIdActionPerformed

    }//GEN-LAST:event_searchIdActionPerformed

    private void searchIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchIdKeyReleased
        id = Integer.parseInt(searchId.getText());
    }//GEN-LAST:event_searchIdKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TransactionActionImplementation tai = new TransactionActionImplementation();
        List<Transaction> transactions  = tai.viewTransaction(1);
        boolean recordFound = false;
        
        for (Transaction transaction : transactions) {
            if (transaction.getTransactionId() == id) {
                recordFound = true;
                t = view(id);
            }
        }
        
        if (!recordFound) {
            destinationComboBox.setSelectedIndex(0);
            passengerTypeComboBox.setSelectedIndex(0);
            seatTypeComboBox.setSelectedIndex(0);
            quantity.setText("");
            amount.setText("");
            total.setText("Total: ");
            change.setText("Change: ");
            JOptionPane.showMessageDialog(this, "No record found!");
            return;
        }
        
        if (t.getAmount() < t.getTotal()) {
            JOptionPane.showMessageDialog(this, "Insuficient amount!");
        }
        populateFieldsbyId(id);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JLabel change;
    private javax.swing.JComboBox<String> destinationComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> passengerTypeComboBox;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField searchId;
    private javax.swing.JComboBox<String> seatTypeComboBox;
    private javax.swing.JLabel total;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
