/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Interface.TransactionActionImplementation;
import static Main.Main.view;
import Models.Transaction;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Jay Vallespin
 */
public class ViewTransaction extends javax.swing.JFrame {
    int id;
    
    /**
     * Creates new form ViewTransaction
     */
    public ViewTransaction() {
        initComponents();
        
        setLocationRelativeTo(null);
    }
    
    void populateFieldsbySearchId(int id) {
        TransactionActionImplementation tai = new TransactionActionImplementation();
        List<Transaction> transactions  = tai.viewTransaction(1);
        Transaction t = new Transaction();
        boolean recordFound = false;
        
        for (Transaction transaction : transactions) {
            if (transaction.getTransactionId() == id) {
                recordFound = true;
                t = view(id);
            }
        }
        
        if (!recordFound) {
            transactionId.setText("ID: ");
            destination.setText("Destination: ");
            passengerType.setText("Passenger Type: ");
            passengerTypePrice.setText("Passenger Type Price: ");
            seatType.setText("Seat Type: ");
            seatTypePrice.setText("Seat Type Price: ");
            quantity.setText("Quantity: ");
            total.setText("Total: ");
            amount.setText("Amount: ");
            change.setText("Change: ");
            date.setText("Date: ");
            JOptionPane.showMessageDialog(this, "No record found!");
            return;
        }
        
        transactionId.setText("ID: " + t.getTransactionId());
        destination.setText("Destination: " + t.getDestination());
        passengerType.setText("Passenger Type: " + t.getPassengerType());
        passengerTypePrice.setText("Passenger Type Price: " + t.getPassengerTypePrice());
        seatType.setText("Seat Type: " + t.getSeatType());
        seatTypePrice.setText("Seat Type Price: " + t.getSeatTypePrice());
        quantity.setText("Quantity: " + t.getQuantity());
        total.setText("Total: " + t.getTotal());
        amount.setText("Amount: " + t.getAmount());
        change.setText("Change: " + t.getChange());
        date.setText("Date: " + t.getCreated_at());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goBackButton = new javax.swing.JButton();
        transactionId = new javax.swing.JLabel();
        destination = new javax.swing.JLabel();
        passengerType = new javax.swing.JLabel();
        passengerTypePrice = new javax.swing.JLabel();
        seatType = new javax.swing.JLabel();
        seatTypePrice = new javax.swing.JLabel();
        quantity = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        change = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        searchId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        goBackButton.setText("Go back");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        transactionId.setText("ID:");

        destination.setText("Destination:");

        passengerType.setText("Passenger Type:");

        passengerTypePrice.setText("Passenger Type Price:");

        seatType.setText("Seat Type:");

        seatTypePrice.setText("Seat Type Price:");

        quantity.setText("Quantity:");

        total.setText("Total:");

        amount.setText("Amount:");

        change.setText("Change:");

        date.setText("Date:");

        searchId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIdActionPerformed(evt);
            }
        });
        searchId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchIdKeyReleased(evt);
            }
        });

        jButton1.setText("Search ID");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goBackButton)
                            .addComponent(change)
                            .addComponent(date)
                            .addComponent(transactionId)
                            .addComponent(destination)
                            .addComponent(passengerType)
                            .addComponent(passengerTypePrice)
                            .addComponent(seatType)
                            .addComponent(seatTypePrice)
                            .addComponent(quantity)
                            .addComponent(total)
                            .addComponent(amount)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchId, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGap(0, 74, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transactionId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(destination)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passengerType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passengerTypePrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seatType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seatTypePrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quantity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(change)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        Home h = new Home();
        
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void searchIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIdActionPerformed

    }//GEN-LAST:event_searchIdActionPerformed

    private void searchIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchIdKeyReleased
        id = Integer.valueOf(searchId.getText());
    }//GEN-LAST:event_searchIdKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        populateFieldsbySearchId(id);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(this, "Print Successfully!");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amount;
    private javax.swing.JLabel change;
    private javax.swing.JLabel date;
    private javax.swing.JLabel destination;
    private javax.swing.JButton goBackButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel passengerType;
    private javax.swing.JLabel passengerTypePrice;
    private javax.swing.JLabel quantity;
    private javax.swing.JTextField searchId;
    private javax.swing.JLabel seatType;
    private javax.swing.JLabel seatTypePrice;
    private javax.swing.JLabel total;
    private javax.swing.JLabel transactionId;
    // End of variables declaration//GEN-END:variables
}
